CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  fullname VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  country VARCHAR(50),
  balance DECIMAL(10, 2),
  is_blocked BOOLEAN DEFAULT FALSE
);